// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateReq struct {
	NewName              string   `protobuf:"bytes,1,opt,name=newName,proto3" json:"newName,omitempty"`
	OldName              string   `protobuf:"bytes,2,opt,name=oldName,proto3" json:"oldName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

func (m *UpdateReq) GetOldName() string {
	if m != nil {
		return m.OldName
	}
	return ""
}

type UpdateResp struct {
	Errno                string    `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string    `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *NameData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResp) Reset()         { *m = UpdateResp{} }
func (m *UpdateResp) String() string { return proto.CompactTextString(m) }
func (*UpdateResp) ProtoMessage()    {}
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *UpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResp.Unmarshal(m, b)
}
func (m *UpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResp.Marshal(b, m, deterministic)
}
func (m *UpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResp.Merge(m, src)
}
func (m *UpdateResp) XXX_Size() int {
	return xxx_messageInfo_UpdateResp.Size(m)
}
func (m *UpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResp proto.InternalMessageInfo

func (m *UpdateResp) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *UpdateResp) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *UpdateResp) GetData() *NameData {
	if m != nil {
		return m.Data
	}
	return nil
}

type NameData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameData) Reset()         { *m = NameData{} }
func (m *NameData) String() string { return proto.CompactTextString(m) }
func (*NameData) ProtoMessage()    {}
func (*NameData) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *NameData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameData.Unmarshal(m, b)
}
func (m *NameData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameData.Marshal(b, m, deterministic)
}
func (m *NameData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameData.Merge(m, src)
}
func (m *NameData) XXX_Size() int {
	return xxx_messageInfo_NameData.Size(m)
}
func (m *NameData) XXX_DiscardUnknown() {
	xxx_messageInfo_NameData.DiscardUnknown(m)
}

var xxx_messageInfo_NameData proto.InternalMessageInfo

func (m *NameData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Errno                string    `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Errmsg               string    `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Data                 *UserInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *Response) GetData() *UserInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserInfo struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard               string   `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserInfo) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *UserInfo) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *UserInfo) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateReq)(nil), "go.micro.srv.user.UpdateReq")
	proto.RegisterType((*UpdateResp)(nil), "go.micro.srv.user.UpdateResp")
	proto.RegisterType((*NameData)(nil), "go.micro.srv.user.NameData")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.user.Response")
	proto.RegisterType((*UserInfo)(nil), "go.micro.srv.user.UserInfo")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7) }

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xe3, 0xac, 0xe3, 0x3f, 0xb3, 0xcb, 0xc2, 0x8a, 0x6d, 0x63, 0x92, 0xa6, 0x04, 0x9f,
	0x72, 0x72, 0x20, 0x7d, 0x80, 0x1e, 0x5a, 0x28, 0x39, 0xb4, 0x05, 0x43, 0xce, 0x46, 0x89, 0xd4,
	0x60, 0x6a, 0x5b, 0xce, 0xc8, 0x49, 0xdf, 0xa7, 0xf4, 0x41, 0x8b, 0xc6, 0x72, 0x1b, 0x68, 0xe8,
	0xa9, 0x17, 0xa3, 0x6f, 0x3e, 0x8d, 0xe6, 0x37, 0xe3, 0x81, 0xb3, 0x1a, 0x55, 0xa3, 0xe6, 0x7b,
	0x2d, 0x91, 0x3e, 0x09, 0x69, 0xf6, 0x6f, 0xab, 0x92, 0x32, 0xdf, 0xa0, 0x4a, 0x34, 0x1e, 0x12,
	0x63, 0xc4, 0xd7, 0x10, 0xae, 0x6a, 0xc1, 0x1b, 0x99, 0xca, 0x1d, 0x8b, 0xc0, 0xaf, 0xe4, 0xcb,
	0x03, 0x2f, 0x65, 0xe4, 0x4c, 0x9d, 0x59, 0x98, 0x76, 0xd2, 0x38, 0xaa, 0x10, 0xe4, 0xf4, 0x5b,
	0xc7, 0xca, 0xf8, 0x19, 0xa0, 0x7b, 0x40, 0xd7, 0xec, 0x3f, 0x0c, 0x24, 0x62, 0xa5, 0x6c, 0x7e,
	0x2b, 0xd8, 0x39, 0x78, 0x12, 0xb1, 0xd4, 0x5b, 0x9b, 0x6c, 0x15, 0x9b, 0x83, 0x2b, 0x78, 0xc3,
	0xa3, 0x5f, 0x53, 0x67, 0xf6, 0x7b, 0x31, 0x4e, 0xbe, 0xe0, 0x25, 0xa6, 0xc4, 0x2d, 0x6f, 0x78,
	0x4a, 0x17, 0xe3, 0x4b, 0x08, 0xba, 0x08, 0x63, 0xe0, 0x1e, 0x91, 0xd2, 0x39, 0x9e, 0x80, 0x9f,
	0xca, 0xdd, 0x5e, 0xea, 0xc6, 0xd8, 0xd5, 0x91, 0x6d, 0xce, 0x71, 0x0e, 0x81, 0xa1, 0x54, 0x95,
	0x96, 0x3f, 0x4e, 0xba, 0xd2, 0x12, 0x97, 0xd5, 0x93, 0xb2, 0xa4, 0x6f, 0x0e, 0x04, 0x5d, 0x88,
	0x0d, 0xc1, 0x37, 0x77, 0xb2, 0x5c, 0x50, 0xb5, 0x41, 0xea, 0x19, 0xb9, 0x14, 0x1f, 0x90, 0xfd,
	0x4f, 0x48, 0x83, 0x50, 0xaa, 0x75, 0x5e, 0x48, 0x2a, 0x16, 0xa6, 0x56, 0xb1, 0x31, 0x84, 0x28,
	0x79, 0x91, 0x51, 0x82, 0x4b, 0x56, 0x60, 0x02, 0xf4, 0x7f, 0x86, 0xe0, 0xe7, 0x22, 0xdb, 0x70,
	0x14, 0xd1, 0xa0, 0xcd, 0xca, 0xc5, 0x0d, 0x47, 0xc1, 0x26, 0x00, 0xfc, 0xc0, 0x1b, 0x8e, 0xd9,
	0x1e, 0x8b, 0xc8, 0x23, 0x2f, 0x6c, 0x23, 0x2b, 0x2c, 0x16, 0xaf, 0x0e, 0xb8, 0x06, 0x93, 0x2d,
	0xe1, 0xcf, 0xbd, 0x69, 0xe8, 0x4e, 0x36, 0xa4, 0x47, 0x27, 0x5a, 0xb4, 0xa3, 0x1d, 0x8d, 0x4f,
	0x7a, 0xed, 0x5c, 0xe3, 0x1e, 0x7b, 0x84, 0xbf, 0xed, 0x46, 0x98, 0x87, 0x88, 0xee, 0xe2, 0xd4,
	0xbc, 0xba, 0xad, 0x1b, 0x4d, 0xbe, 0x71, 0x75, 0x1d, 0xf7, 0xd6, 0x1e, 0x6d, 0xef, 0xd5, 0x7b,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x2b, 0x55, 0x12, 0xd6, 0x02, 0x00, 0x00,
}
